title: Anthony Rondini
markdown: kramdown

# for atom feed
author:
  name: Anthony Rondini
  email: anthony.rondini227@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections/_posts
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
remote_theme: jekyll-theme-serial-programmer
